openapi: 3.0.0
info:
  title: Laravel Routes
  version: 1.0.0
paths:
  /api/V1/categories:
    get:
      operationId: indexCategories
      tags:
        - Categories
      summary: List all categories
      responses:
        '200':
          description: OK
    post:
      operationId: storeCategory
      tags:
        - Categories
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Created
  /api/V1/categories/{category}:
    get:
      operationId: showCategory
      tags:
        - Categories
      summary: Get a single category
      parameters:
        - name: category
          in: path
          required: true
          description: Category ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    put:
      operationId: updateCategory
      tags:
        - Categories
      summary: Update a category
      parameters:
        - name: category
          in: path
          required: true
          description: Category ID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '200':
          description: OK
    delete:
      operationId: deleteCategory
      tags:
        - Categories
      summary: Delete a category
      parameters:
        - name: category
          in: path
          required: true
          description: Category ID
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No content
  /api/V1/commentaires:
    get:
      operationId: indexCommentaires
      tags:
        - Commentaires
      summary: List all commentaires
      responses:
        '200':
          description: OK
    post:
      operationId: storeCommentaire
      tags:
        - Commentaires
      summary: Create a new commentaire
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentaireInput'
      responses:
        '201':
          description: Created
  /api/V1/commentaires/{commentaire}:
    get:
      operationId: showCommentaire
      tags:
        - Commentaires
      summary: Get a single commentaire
      parameters:
        - name: commentaire
          in: path
          required: true
          description: Commentaire ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    put:
      operationId: updateCommentaire
      tags:
        - Commentaires
      summary: Update a commentaire
      parameters:
        - name: commentaire
          in: path
          required: true
          description: Commentaire ID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentaireInput'
      responses:
        '200':
          description: OK
    delete:
      operationId: deleteCommentaire
      tags:
        - Comment
