site_name: RESREL-SERVER Documentation

nav:
  - Getting started: index.md
  - Errors: 
    - Request errors: errors/#request-errors
    - Server errors: errors/#server-errors
  - Operations: 
    - Pagination: operations/#pagination
    - Sorting: operations/#sorting
    - Filtering: operations/#filtering
    - Aggregating: operations/#aggregating
  - Endpoints: 
    - Summary: endpoints-summary.md
    - List of endpoints:
      - Authentification: endpoints/authentication.md
      - Categories: endpoints/categories.md
      - Comments: endpoints/comments.md
      - Favorites: enpoints/#favorites
      - Groups: enpoints/#groups
      - Pieces jointes: enpoints/#pieces-jointes
      - Relations: enpoints/#relations
      - Comment responses: enpoints/#comment-responses
      - Resources: enpoints/#resources
      - Roles: enpoints/#roles
      - Search: enpoints/#search
      - Relation types: enpoints/#relation-types
      - Users: enpoints/#users

theme:
  name: 'material'
  logo: 'docs-favicon.png'
  favicon: 'docs-favicon.png'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.footer
#    - navigation.tabs

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html #grids (to test)
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg