name: Codacy Coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravelpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1.15'
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Setup Laravel environment
      run: cp .env.testing .env
      
    - name: Run PHPUnit tests with code coverage
      run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

    - name: Install Codacy Coverage Reporter
      run: composer global require codacy/coverage

    - name: Upload coverage report to Codacy
      run: ~/.config/composer/vendor/bin/codacycoverage clover build/logs/clover.xml
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
